export GOOGLE_APPLICATION_CREDENTIALS="" #Path to the service account key file in JSON format. "/home/Maksym/file.json"
export TF_VAR_user_name="" # The user that we should use for the SSH connection. "Maksym"
export TF_VAR_p_key="" # The path of an SSH key to use for the connection. ".ssh/id_key"
export TF_VAR_home_dir="" # Home user directory. "/home/Maksym"
export TF_VAR_ansible_vault_key="" # Home user directory. "/home/Maksym"
export GOOGLE_PROJECT=""# The ID of the project  "myproject-123456" 
